"""remove asvs-specific fields

Revision ID: 3b6307d5c573
Revises: 89dc43087e8f
Create Date: 2026-06-21 17:12:07.302730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b6307d5c573'
down_revision: Union[str, Sequence[str], None] = '89dc43087e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standards_asvsleveldefinition_ingestion_job_id'), table_name='standards_asvsleveldefinition')
    op.drop_table('standards_asvsleveldefinition')
    op.drop_column('reviews_review', 'asvs_level_override')
    op.alter_column('standards_categorycontrolsummaryrequirement', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('standards_categorycontrolsummaryrequirement', 'category_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('standards_categorycontrolsummaryrequirement', 'ingestion_job_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('standards_categorycontrolsummaryrequirement', 'parent_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_cfsr_asvs_level'), table_name='standards_categorycontrolsummaryrequirement')
    op.drop_index(op.f('ix_cfsr_category_id'), table_name='standards_categorycontrolsummaryrequirement')
    op.drop_index(op.f('ix_cfsr_ingestion_job_id'), table_name='standards_categorycontrolsummaryrequirement')
    op.drop_index(op.f('ix_cfsr_parent_id'), table_name='standards_categorycontrolsummaryrequirement')
    op.drop_index(op.f('ix_cfsr_stable_key'), table_name='standards_categorycontrolsummaryrequirement')
    op.create_index(op.f('ix_standards_categorycontrolsummaryrequirement_category_id'), 'standards_categorycontrolsummaryrequirement', ['category_id'], unique=False)
    op.create_index(op.f('ix_standards_categorycontrolsummaryrequirement_ingestion_job_id'), 'standards_categorycontrolsummaryrequirement', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_standards_categorycontrolsummaryrequirement_parent_id'), 'standards_categorycontrolsummaryrequirement', ['parent_id'], unique=False)
    op.create_index(op.f('ix_standards_categorycontrolsummaryrequirement_stable_key'), 'standards_categorycontrolsummaryrequirement', ['stable_key'], unique=False)
    op.drop_column('standards_categorycontrolsummaryrequirement', 'asvs_level')
    op.drop_index(op.f('ix_standards_categorydiagramrequirement_asvs_level'), table_name='standards_categorydiagramrequirement')
    op.drop_column('standards_categorydiagramrequirement', 'asvs_level')
    op.drop_index(op.f('ix_standards_categoryparameterchild_asvs_level'), table_name='standards_categoryparameterchild')
    op.drop_column('standards_categoryparameterchild', 'asvs_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards_categoryparameterchild', sa.Column('asvs_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_standards_categoryparameterchild_asvs_level'), 'standards_categoryparameterchild', ['asvs_level'], unique=False)
    op.add_column('standards_categorydiagramrequirement', sa.Column('asvs_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_standards_categorydiagramrequirement_asvs_level'), 'standards_categorydiagramrequirement', ['asvs_level'], unique=False)
    op.add_column('standards_categorycontrolsummaryrequirement', sa.Column('asvs_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_standards_categorycontrolsummaryrequirement_stable_key'), table_name='standards_categorycontrolsummaryrequirement')
    op.drop_index(op.f('ix_standards_categorycontrolsummaryrequirement_parent_id'), table_name='standards_categorycontrolsummaryrequirement')
    op.drop_index(op.f('ix_standards_categorycontrolsummaryrequirement_ingestion_job_id'), table_name='standards_categorycontrolsummaryrequirement')
    op.drop_index(op.f('ix_standards_categorycontrolsummaryrequirement_category_id'), table_name='standards_categorycontrolsummaryrequirement')
    op.create_index(op.f('ix_cfsr_stable_key'), 'standards_categorycontrolsummaryrequirement', ['stable_key'], unique=False)
    op.create_index(op.f('ix_cfsr_parent_id'), 'standards_categorycontrolsummaryrequirement', ['parent_id'], unique=False)
    op.create_index(op.f('ix_cfsr_ingestion_job_id'), 'standards_categorycontrolsummaryrequirement', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_cfsr_category_id'), 'standards_categorycontrolsummaryrequirement', ['category_id'], unique=False)
    op.create_index(op.f('ix_cfsr_asvs_level'), 'standards_categorycontrolsummaryrequirement', ['asvs_level'], unique=False)
    op.alter_column('standards_categorycontrolsummaryrequirement', 'parent_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('standards_categorycontrolsummaryrequirement', 'ingestion_job_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('standards_categorycontrolsummaryrequirement', 'category_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('standards_categorycontrolsummaryrequirement', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('reviews_review', sa.Column('asvs_level_override', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('standards_asvsleveldefinition',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ingestion_job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('classification_guidance', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_quote', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('context_marker', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('level = ANY (ARRAY[1, 2, 3])', name=op.f('ck_asvs_level_definition_range')),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['standards_standingestionjob.id'], name=op.f('standards_asvsleveldefinition_ingestion_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('standards_asvsleveldefinition_pkey')),
    sa.UniqueConstraint('ingestion_job_id', 'level', name=op.f('unique_asvs_level_definition_per_job'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_standards_asvsleveldefinition_ingestion_job_id'), 'standards_asvsleveldefinition', ['ingestion_job_id'], unique=False)
    # ### end Alembic commands ###
