"""remove status

Revision ID: 4b9a1add11bd
Revises: 6b1c4fd9f2a1
Create Date: 2026-06-10 23:23:21.867366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9a1add11bd'
down_revision: Union[str, Sequence[str], None] = '6b1c4fd9f2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_finding_status_sev'), table_name='reviews_finding')
    op.drop_index(op.f('ix_reviews_finding_status'), table_name='reviews_finding')
    op.create_index('idx_finding_severity', 'reviews_finding', ['severity'], unique=False)
    op.drop_column('reviews_finding', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews_finding', sa.Column('status', sa.VARCHAR(length=24), autoincrement=False, nullable=False))
    op.drop_index('idx_finding_severity', table_name='reviews_finding')
    op.create_index(op.f('ix_reviews_finding_status'), 'reviews_finding', ['status'], unique=False)
    op.create_index(op.f('idx_finding_status_sev'), 'reviews_finding', ['status', 'severity'], unique=False)
    # ### end Alembic commands ###
