"""remove asvslevel table

Revision ID: 6205890a3380
Revises: dadbbca54a8e
Create Date: 2026-06-13 14:43:59.987546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6205890a3380'
down_revision: Union[str, Sequence[str], None] = 'dadbbca54a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('standards_categorydiagramrequirement_asvs_level_fkey'), 'standards_categorydiagramrequirement', type_='foreignkey')
    op.drop_constraint(op.f('standards_categoryparameterchild_asvs_level_fkey'), 'standards_categoryparameterchild', type_='foreignkey')
    op.drop_index(op.f('ix_standards_asvslevel_code'), table_name='standards_asvslevel')
    op.drop_table('standards_asvslevel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('standards_categoryparameterchild_asvs_level_fkey'), 'standards_categoryparameterchild', 'standards_asvslevel', ['asvs_level'], ['level'], ondelete='SET NULL')
    op.create_foreign_key(op.f('standards_categorydiagramrequirement_asvs_level_fkey'), 'standards_categorydiagramrequirement', 'standards_asvslevel', ['asvs_level'], ['level'], ondelete='SET NULL')
    op.create_table('standards_asvslevel',
    sa.Column('level', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('classification_guidance', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('level = ANY (ARRAY[1, 2, 3])', name=op.f('ck_asvs_level_range')),
    sa.PrimaryKeyConstraint('level', name=op.f('standards_asvslevel_pkey'))
    )
    op.create_index(op.f('ix_standards_asvslevel_code'), 'standards_asvslevel', ['code'], unique=True)
    # ### end Alembic commands ###
