"""add celery_task_id

Revision ID: 706007a24faf
Revises: 3df3d85505af
Create Date: 2026-07-04 17:58:05.535262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706007a24faf'
down_revision: Union[str, Sequence[str], None] = '3df3d85505af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designs_designpreparation', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_designs_designpreparation_celery_task_id'), 'designs_designpreparation', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_designs_designpreparation_celery_task_id'), table_name='designs_designpreparation')
    op.drop_column('designs_designpreparation', 'celery_task_id')
    # ### end Alembic commands ###
