"""add_diagram_type_to_categorydiagramrequirement

Revision ID: 7dd0b1900779
Revises: 936b64336594
Create Date: 2026-06-26 10:46:48.081719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dd0b1900779'
down_revision: Union[str, Sequence[str], None] = '936b64336594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_designprep_graph_relation_embedding_hnsw'), table_name='designs_designpreparationgraphrelation', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_designprep_graph_relation_preparation_relation'), table_name='designs_designpreparationgraphrelation')
    op.drop_index(op.f('idx_designprep_graph_relation_preparation_source'), table_name='designs_designpreparationgraphrelation')
    op.drop_index(op.f('idx_designprep_graph_relation_preparation_target'), table_name='designs_designpreparationgraphrelation')
    op.drop_index(op.f('ix_designs_designpreparationgraphrelation_content_hash'), table_name='designs_designpreparationgraphrelation')
    op.drop_index(op.f('ix_designs_designpreparationgraphrelation_preparation_id'), table_name='designs_designpreparationgraphrelation')
    op.drop_table('designs_designpreparationgraphrelation')
    op.drop_index(op.f('idx_designprep_graph_entity_embedding_hnsw'), table_name='designs_designpreparationgraphentity', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_designprep_graph_entity_preparation_entity'), table_name='designs_designpreparationgraphentity')
    op.drop_index(op.f('idx_designprep_graph_entity_preparation_type'), table_name='designs_designpreparationgraphentity')
    op.drop_index(op.f('ix_designs_designpreparationgraphentity_content_hash'), table_name='designs_designpreparationgraphentity')
    op.drop_index(op.f('ix_designs_designpreparationgraphentity_preparation_id'), table_name='designs_designpreparationgraphentity')
    op.drop_table('designs_designpreparationgraphentity')
    op.drop_column('designs_designpreparation', 'graph_artifact_object_key')
    op.add_column('standards_categorydiagramrequirement', sa.Column('diagram_type', sa.String(length=64), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standards_categorydiagramrequirement', 'diagram_type')
    op.add_column('designs_designpreparation', sa.Column('graph_artifact_object_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.create_table('designs_designpreparationgraphentity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('preparation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source_block_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('source_pages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['preparation_id'], ['designs_designpreparation.id'], name=op.f('designs_designpreparationgraphentity_preparation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('designs_designpreparationgraphentity_pkey'))
    )
    op.create_index(op.f('ix_designs_designpreparationgraphentity_preparation_id'), 'designs_designpreparationgraphentity', ['preparation_id'], unique=False)
    op.create_index(op.f('ix_designs_designpreparationgraphentity_content_hash'), 'designs_designpreparationgraphentity', ['content_hash'], unique=False)
    op.create_index(op.f('idx_designprep_graph_entity_preparation_type'), 'designs_designpreparationgraphentity', ['preparation_id', 'entity_type'], unique=False)
    op.create_index(op.f('idx_designprep_graph_entity_preparation_entity'), 'designs_designpreparationgraphentity', ['preparation_id', 'entity_id'], unique=True)
    op.create_index(op.f('idx_designprep_graph_entity_embedding_hnsw'), 'designs_designpreparationgraphentity', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('designs_designpreparationgraphrelation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('preparation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_entity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('target_entity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('relation_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('protocol', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('requires_auth', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('source_block_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('source_pages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['preparation_id'], ['designs_designpreparation.id'], name=op.f('designs_designpreparationgraphrelation_preparation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('designs_designpreparationgraphrelation_pkey'))
    )
    op.create_index(op.f('ix_designs_designpreparationgraphrelation_preparation_id'), 'designs_designpreparationgraphrelation', ['preparation_id'], unique=False)
    op.create_index(op.f('ix_designs_designpreparationgraphrelation_content_hash'), 'designs_designpreparationgraphrelation', ['content_hash'], unique=False)
    op.create_index(op.f('idx_designprep_graph_relation_preparation_target'), 'designs_designpreparationgraphrelation', ['preparation_id', 'target_entity_id'], unique=False)
    op.create_index(op.f('idx_designprep_graph_relation_preparation_source'), 'designs_designpreparationgraphrelation', ['preparation_id', 'source_entity_id'], unique=False)
    op.create_index(op.f('idx_designprep_graph_relation_preparation_relation'), 'designs_designpreparationgraphrelation', ['preparation_id', 'relation_id'], unique=True)
    op.create_index(op.f('idx_designprep_graph_relation_embedding_hnsw'), 'designs_designpreparationgraphrelation', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
