"""remove_details_from_parameter_child

Revision ID: 83864b582e8b
Revises: d6b82b2187db
Create Date: 2026-06-29 18:08:42.153121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83864b582e8b'
down_revision: Union[str, Sequence[str], None] = 'd6b82b2187db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standards_categoryparameterchild', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards_categoryparameterchild', sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
