"""single category review

Revision ID: 8c82b8701ebc
Revises: 3f4f8d2ab1c1
Create Date: 2026-06-16 13:55:26.194019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c82b8701ebc'
down_revision: Union[str, Sequence[str], None] = '3f4f8d2ab1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews_review_categories')
    op.add_column('reviews_review', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reviews_review_category_id'), 'reviews_review', ['category_id'], unique=False)
    op.create_foreign_key(None, 'reviews_review', 'standards_standardcategory', ['category_id'], ['id'], ondelete='SET NULL')
    op.alter_column('standards_categorydiagramrequirementembedding', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('standards_categorydiagramrequirementembedding', 'diagram_requirement_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('standards_categorydiagramrequirementembedding', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('standards_categorydiagramrequirementembedding', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_diagramreqembedding_req_id'), table_name='standards_categorydiagramrequirementembedding')
    op.drop_index(op.f('ix_standards_categoryparameterembedding_content_hash'), table_name='standards_categoryparameterembedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_standards_categoryparameterembedding_content_hash'), 'standards_categoryparameterembedding', ['content_hash'], unique=False)
    op.create_index(op.f('idx_diagramreqembedding_req_id'), 'standards_categorydiagramrequirementembedding', ['diagram_requirement_id'], unique=False)
    op.alter_column('standards_categorydiagramrequirementembedding', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('standards_categorydiagramrequirementembedding', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('standards_categorydiagramrequirementembedding', 'diagram_requirement_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('standards_categorydiagramrequirementembedding', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'reviews_review', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_review_category_id'), table_name='reviews_review')
    op.drop_column('reviews_review', 'category_id')
    op.create_table('reviews_review_categories',
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['standards_standardcategory.id'], name=op.f('reviews_review_categories_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews_review.id'], name=op.f('reviews_review_categories_review_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id', 'category_id', name=op.f('reviews_review_categories_pkey'))
    )
    # ### end Alembic commands ###
