"""add progress

Revision ID: 936b64336594
Revises: 721bd7f4f69e
Create Date: 2026-06-22 13:23:48.956114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '936b64336594'
down_revision: Union[str, Sequence[str], None] = '721bd7f4f69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designs_design', sa.Column('preparation_progress_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('designs_designpreparation', sa.Column('progress_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('designs_designpreparation', 'progress_json')
    op.drop_column('designs_design', 'preparation_progress_json')
    # ### end Alembic commands ###
