"""remove CFSRs

Revision ID: 9b0d8722827d
Revises: 3b6307d5c573
Create Date: 2026-06-22 00:12:47.258595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b0d8722827d'
down_revision: Union[str, Sequence[str], None] = '3b6307d5c573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standards_categorycontrolsummaryrequirement_category_id'), table_name='standards_categorycontrolsummaryrequirement')
    op.drop_index(op.f('ix_standards_categorycontrolsummaryrequirement_ingestion_job_id'), table_name='standards_categorycontrolsummaryrequirement')
    op.drop_index(op.f('ix_standards_categorycontrolsummaryrequirement_parent_id'), table_name='standards_categorycontrolsummaryrequirement')
    op.drop_index(op.f('ix_standards_categorycontrolsummaryrequirement_stable_key'), table_name='standards_categorycontrolsummaryrequirement')
    op.drop_table('standards_categorycontrolsummaryrequirement')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standards_categorycontrolsummaryrequirement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingestion_job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stable_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requirement_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('analysis_hint', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('covered_child_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('ordinal', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['standards_standardcategory.id'], name=op.f('standards_categorycontrolsummaryrequirement_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['standards_standingestionjob.id'], name=op.f('standards_categorycontrolsummaryrequireme_ingestion_job_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['standards_categoryparameterparent.id'], name=op.f('standards_categorycontrolsummaryrequirement_parent_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('standards_categorycontrolsummaryrequirement_pkey')),
    sa.UniqueConstraint('category_id', 'stable_key', name=op.f('unique_cfsr_key_per_category'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_standards_categorycontrolsummaryrequirement_stable_key'), 'standards_categorycontrolsummaryrequirement', ['stable_key'], unique=False)
    op.create_index(op.f('ix_standards_categorycontrolsummaryrequirement_parent_id'), 'standards_categorycontrolsummaryrequirement', ['parent_id'], unique=False)
    op.create_index(op.f('ix_standards_categorycontrolsummaryrequirement_ingestion_job_id'), 'standards_categorycontrolsummaryrequirement', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_standards_categorycontrolsummaryrequirement_category_id'), 'standards_categorycontrolsummaryrequirement', ['category_id'], unique=False)
    # ### end Alembic commands ###
