"""initial_schema

Revision ID: ad2d18ce0ff1
Revises: 
Create Date: 2026-06-07 15:37:13.646580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ad2d18ce0ff1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designs_design',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document', sa.String(length=1024), nullable=False),
    sa.Column('source_format', sa.String(length=10), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processing_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standards_standardcategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_standards_standardcategory_code'), 'standards_standardcategory', ['code'], unique=True)
    op.create_table('standards_standingestionjob',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['standards_standardcategory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_standingestionjob_category_id'), 'standards_standingestionjob', ['category_id'], unique=False)
    op.create_index('unique_active_ingestion_job_per_category', 'standards_standingestionjob', ['category_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('reviews_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs_design.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['standards_standingestionjob.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_design_status', 'reviews_review', ['design_id', 'status'], unique=False)
    op.create_index(op.f('ix_reviews_review_celery_task_id'), 'reviews_review', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_reviews_review_design_id'), 'reviews_review', ['design_id'], unique=False)
    op.create_index(op.f('ix_reviews_review_ingestion_job_id'), 'reviews_review', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_reviews_review_status'), 'reviews_review', ['status'], unique=False)
    op.create_table('standards_categoryparameterparent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_job_id', sa.Integer(), nullable=True),
    sa.Column('stable_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_normalized', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['standards_standardcategory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['standards_standingestionjob.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'stable_key', name='unique_parent_key_per_category')
    )
    op.create_index(op.f('ix_standards_categoryparameterparent_category_id'), 'standards_categoryparameterparent', ['category_id'], unique=False)
    op.create_index(op.f('ix_standards_categoryparameterparent_ingestion_job_id'), 'standards_categoryparameterparent', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_standards_categoryparameterparent_stable_key'), 'standards_categoryparameterparent', ['stable_key'], unique=False)
    op.create_index(op.f('ix_standards_categoryparameterparent_title_normalized'), 'standards_categoryparameterparent', ['title_normalized'], unique=False)
    op.create_table('standards_standardsourcedocument',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingestion_job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('document_version_label', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['standards_standingestionjob.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_standardsourcedocument_content_hash'), 'standards_standardsourcedocument', ['content_hash'], unique=False)
    op.create_index(op.f('ix_standards_standardsourcedocument_ingestion_job_id'), 'standards_standardsourcedocument', ['ingestion_job_id'], unique=False)
    op.create_table('ai_reviewanalysisworkpack',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=False),
    sa.Column('progress_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews_review.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_workpack_created', 'ai_reviewanalysisworkpack', ['created_at'], unique=False)
    op.create_index('idx_ai_workpack_review_state', 'ai_reviewanalysisworkpack', ['review_id', 'state'], unique=False)
    op.create_index(op.f('ix_ai_reviewanalysisworkpack_review_id'), 'ai_reviewanalysisworkpack', ['review_id'], unique=False)
    op.create_index(op.f('ix_ai_reviewanalysisworkpack_state'), 'ai_reviewanalysisworkpack', ['state'], unique=False)
    op.create_table('reviews_review_categories',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['standards_standardcategory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews_review.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id', 'category_id')
    )
    op.create_table('standards_categoryparameterchild',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('stable_key', sa.String(length=255), nullable=False),
    sa.Column('requirement_text', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('requirement_text_normalized', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['standards_categoryparameterparent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'stable_key', name='unique_child_key_per_parent')
    )
    op.create_index(op.f('ix_standards_categoryparameterchild_parent_id'), 'standards_categoryparameterchild', ['parent_id'], unique=False)
    op.create_index(op.f('ix_standards_categoryparameterchild_stable_key'), 'standards_categoryparameterchild', ['stable_key'], unique=False)
    op.create_table('ai_reviewanalysisworkitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workpack_id', sa.Uuid(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('ingestion_job_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['standards_standardcategory.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['standards_standingestionjob.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parameter_id'], ['standards_categoryparameterchild.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workpack_id'], ['ai_reviewanalysisworkpack.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_workitem_pack_state', 'ai_reviewanalysisworkitem', ['workpack_id', 'state'], unique=False)
    op.create_index(op.f('ix_ai_reviewanalysisworkitem_category_id'), 'ai_reviewanalysisworkitem', ['category_id'], unique=False)
    op.create_index(op.f('ix_ai_reviewanalysisworkitem_ingestion_job_id'), 'ai_reviewanalysisworkitem', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_ai_reviewanalysisworkitem_parameter_id'), 'ai_reviewanalysisworkitem', ['parameter_id'], unique=False)
    op.create_index(op.f('ix_ai_reviewanalysisworkitem_state'), 'ai_reviewanalysisworkitem', ['state'], unique=False)
    op.create_index(op.f('ix_ai_reviewanalysisworkitem_workpack_id'), 'ai_reviewanalysisworkitem', ['workpack_id'], unique=False)
    op.create_table('reviews_finding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('parent_parameter_id', sa.Integer(), nullable=True),
    sa.Column('child_parameter_id', sa.Integer(), nullable=True),
    sa.Column('finding_type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('met_status', sa.String(length=16), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=24), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('severity_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hunter_reasoning', sa.String(), nullable=True),
    sa.Column('critic_reasoning', sa.String(), nullable=True),
    sa.Column('mediator_reasoning', sa.String(), nullable=True),
    sa.Column('hunter_thought_process', sa.String(), nullable=True),
    sa.Column('critic_thought_process', sa.String(), nullable=True),
    sa.Column('mediator_thought_process', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('requirement_reference', sa.String(length=128), nullable=True),
    sa.Column('requirement_text', sa.String(), nullable=True),
    sa.Column('requirement_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diagram_id', sa.String(length=64), nullable=True),
    sa.Column('diagram_caption', sa.String(), nullable=True),
    sa.Column('vision_reasoning', sa.String(), nullable=True),
    sa.Column('vision_thought_process', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['standards_standardcategory.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_parameter_id'], ['standards_categoryparameterchild.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_parameter_id'], ['standards_categoryparameterparent.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews_review.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_finding_cat_created', 'reviews_finding', ['category_id', 'created_at'], unique=False)
    op.create_index('idx_finding_met_conf', 'reviews_finding', ['met_status', 'confidence_score'], unique=False)
    op.create_index('idx_finding_review_met', 'reviews_finding', ['review_id', 'met_status'], unique=False)
    op.create_index('idx_finding_review_type', 'reviews_finding', ['review_id', 'finding_type'], unique=False)
    op.create_index('idx_finding_status_sev', 'reviews_finding', ['status', 'severity'], unique=False)
    op.create_index(op.f('ix_reviews_finding_category_id'), 'reviews_finding', ['category_id'], unique=False)
    op.create_index(op.f('ix_reviews_finding_child_parameter_id'), 'reviews_finding', ['child_parameter_id'], unique=False)
    op.create_index(op.f('ix_reviews_finding_diagram_id'), 'reviews_finding', ['diagram_id'], unique=False)
    op.create_index(op.f('ix_reviews_finding_finding_type'), 'reviews_finding', ['finding_type'], unique=False)
    op.create_index(op.f('ix_reviews_finding_met_status'), 'reviews_finding', ['met_status'], unique=False)
    op.create_index(op.f('ix_reviews_finding_parent_parameter_id'), 'reviews_finding', ['parent_parameter_id'], unique=False)
    op.create_index(op.f('ix_reviews_finding_requirement_reference'), 'reviews_finding', ['requirement_reference'], unique=False)
    op.create_index(op.f('ix_reviews_finding_review_id'), 'reviews_finding', ['review_id'], unique=False)
    op.create_index(op.f('ix_reviews_finding_severity'), 'reviews_finding', ['severity'], unique=False)
    op.create_index(op.f('ix_reviews_finding_status'), 'reviews_finding', ['status'], unique=False)
    op.create_table('standards_categoryparameterembedding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parameter_type', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_dim', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['standards_categoryparameterchild.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['standards_categoryparameterparent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('embedding_hnsw_idx', 'standards_categoryparameterembedding', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_categoryparameterembedding_content_hash', 'standards_categoryparameterembedding', ['content_hash'], unique=False)
    op.create_index('idx_categoryparameterembedding_type_active', 'standards_categoryparameterembedding', ['parameter_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_standards_categoryparameterembedding_child_id'), 'standards_categoryparameterembedding', ['child_id'], unique=False)
    op.create_index(op.f('ix_standards_categoryparameterembedding_content_hash'), 'standards_categoryparameterembedding', ['content_hash'], unique=False)
    op.create_index(op.f('ix_standards_categoryparameterembedding_parent_id'), 'standards_categoryparameterembedding', ['parent_id'], unique=False)
    op.create_table('reviews_citationanchor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('anchor_type', sa.String(length=16), nullable=False),
    sa.Column('block_id', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('bbox_x0', sa.Float(), nullable=True),
    sa.Column('bbox_y0', sa.Float(), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('quoted_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['reviews_finding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_citationanchor_finding_page', 'reviews_citationanchor', ['finding_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_reviews_citationanchor_block_id'), 'reviews_citationanchor', ['block_id'], unique=False)
    op.create_index(op.f('ix_reviews_citationanchor_finding_id'), 'reviews_citationanchor', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_citationanchor_finding_id'), table_name='reviews_citationanchor')
    op.drop_index(op.f('ix_reviews_citationanchor_block_id'), table_name='reviews_citationanchor')
    op.drop_index('idx_citationanchor_finding_page', table_name='reviews_citationanchor')
    op.drop_table('reviews_citationanchor')
    op.drop_index(op.f('ix_standards_categoryparameterembedding_parent_id'), table_name='standards_categoryparameterembedding')
    op.drop_index(op.f('ix_standards_categoryparameterembedding_content_hash'), table_name='standards_categoryparameterembedding')
    op.drop_index(op.f('ix_standards_categoryparameterembedding_child_id'), table_name='standards_categoryparameterembedding')
    op.drop_index('idx_categoryparameterembedding_type_active', table_name='standards_categoryparameterembedding')
    op.drop_index('idx_categoryparameterembedding_content_hash', table_name='standards_categoryparameterembedding')
    op.drop_index('embedding_hnsw_idx', table_name='standards_categoryparameterembedding', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('standards_categoryparameterembedding')
    op.drop_index(op.f('ix_reviews_finding_status'), table_name='reviews_finding')
    op.drop_index(op.f('ix_reviews_finding_severity'), table_name='reviews_finding')
    op.drop_index(op.f('ix_reviews_finding_review_id'), table_name='reviews_finding')
    op.drop_index(op.f('ix_reviews_finding_requirement_reference'), table_name='reviews_finding')
    op.drop_index(op.f('ix_reviews_finding_parent_parameter_id'), table_name='reviews_finding')
    op.drop_index(op.f('ix_reviews_finding_met_status'), table_name='reviews_finding')
    op.drop_index(op.f('ix_reviews_finding_finding_type'), table_name='reviews_finding')
    op.drop_index(op.f('ix_reviews_finding_diagram_id'), table_name='reviews_finding')
    op.drop_index(op.f('ix_reviews_finding_child_parameter_id'), table_name='reviews_finding')
    op.drop_index(op.f('ix_reviews_finding_category_id'), table_name='reviews_finding')
    op.drop_index('idx_finding_status_sev', table_name='reviews_finding')
    op.drop_index('idx_finding_review_type', table_name='reviews_finding')
    op.drop_index('idx_finding_review_met', table_name='reviews_finding')
    op.drop_index('idx_finding_met_conf', table_name='reviews_finding')
    op.drop_index('idx_finding_cat_created', table_name='reviews_finding')
    op.drop_table('reviews_finding')
    op.drop_index(op.f('ix_ai_reviewanalysisworkitem_workpack_id'), table_name='ai_reviewanalysisworkitem')
    op.drop_index(op.f('ix_ai_reviewanalysisworkitem_state'), table_name='ai_reviewanalysisworkitem')
    op.drop_index(op.f('ix_ai_reviewanalysisworkitem_parameter_id'), table_name='ai_reviewanalysisworkitem')
    op.drop_index(op.f('ix_ai_reviewanalysisworkitem_ingestion_job_id'), table_name='ai_reviewanalysisworkitem')
    op.drop_index(op.f('ix_ai_reviewanalysisworkitem_category_id'), table_name='ai_reviewanalysisworkitem')
    op.drop_index('idx_ai_workitem_pack_state', table_name='ai_reviewanalysisworkitem')
    op.drop_table('ai_reviewanalysisworkitem')
    op.drop_index(op.f('ix_standards_categoryparameterchild_stable_key'), table_name='standards_categoryparameterchild')
    op.drop_index(op.f('ix_standards_categoryparameterchild_parent_id'), table_name='standards_categoryparameterchild')
    op.drop_table('standards_categoryparameterchild')
    op.drop_table('reviews_review_categories')
    op.drop_index(op.f('ix_ai_reviewanalysisworkpack_state'), table_name='ai_reviewanalysisworkpack')
    op.drop_index(op.f('ix_ai_reviewanalysisworkpack_review_id'), table_name='ai_reviewanalysisworkpack')
    op.drop_index('idx_ai_workpack_review_state', table_name='ai_reviewanalysisworkpack')
    op.drop_index('idx_ai_workpack_created', table_name='ai_reviewanalysisworkpack')
    op.drop_table('ai_reviewanalysisworkpack')
    op.drop_index(op.f('ix_standards_standardsourcedocument_ingestion_job_id'), table_name='standards_standardsourcedocument')
    op.drop_index(op.f('ix_standards_standardsourcedocument_content_hash'), table_name='standards_standardsourcedocument')
    op.drop_table('standards_standardsourcedocument')
    op.drop_index(op.f('ix_standards_categoryparameterparent_title_normalized'), table_name='standards_categoryparameterparent')
    op.drop_index(op.f('ix_standards_categoryparameterparent_stable_key'), table_name='standards_categoryparameterparent')
    op.drop_index(op.f('ix_standards_categoryparameterparent_ingestion_job_id'), table_name='standards_categoryparameterparent')
    op.drop_index(op.f('ix_standards_categoryparameterparent_category_id'), table_name='standards_categoryparameterparent')
    op.drop_table('standards_categoryparameterparent')
    op.drop_index(op.f('ix_reviews_review_status'), table_name='reviews_review')
    op.drop_index(op.f('ix_reviews_review_ingestion_job_id'), table_name='reviews_review')
    op.drop_index(op.f('ix_reviews_review_design_id'), table_name='reviews_review')
    op.drop_index(op.f('ix_reviews_review_celery_task_id'), table_name='reviews_review')
    op.drop_index('idx_review_design_status', table_name='reviews_review')
    op.drop_table('reviews_review')
    op.drop_index('unique_active_ingestion_job_per_category', table_name='standards_standingestionjob', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_standards_standingestionjob_category_id'), table_name='standards_standingestionjob')
    op.drop_table('standards_standingestionjob')
    op.drop_index(op.f('ix_standards_standardcategory_code'), table_name='standards_standardcategory')
    op.drop_table('standards_standardcategory')
    op.drop_table('designs_design')
    # ### end Alembic commands ###
