"""add active boolean for requirements

Revision ID: d6b82b2187db
Revises: d4a72f8b1c09
Create Date: 2026-06-29 10:07:44.942480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b82b2187db'
down_revision: Union[str, Sequence[str], None] = 'd4a72f8b1c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards_categoryparameterchild', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('standards_categoryparameterparent', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standards_categoryparameterparent', 'is_active')
    op.drop_column('standards_categoryparameterchild', 'is_active')
    # ### end Alembic commands ###
